### ISSUE TITLE
Can't build in production mode

### ISSUE THREAD

**Issue by TobiasBreuer** [JulCesWhat/angular5-monaco-editor-loader#1]
Hi, and first of all thanks for sharing this loader!  
I'm integrating the monaco editor into my angular based application. Everything is working great in the normal build environment. When trying the build in productive environment however  
`ng build --prod`  
the build will fail with an error that the monaco-editor-loader cannot be resolved:
`ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'monaco-editor-loader' in 'D:\GitRepositories\angular5-monaco-editor-loader\demo\src\app'`

The error above is the result when trying to build the demo application in this repository in production mode. The same happens to me in my application.

**Comment by TobiasBreuer** [comment]
It turns out, that the build will succeed in production mode, only if you set aot to be false. So your library isn't aot compatible at the moment. If I find some time I will have a closer look. But at the moment I don't see a chance to take care of that...

**Comment by JulCesWhat** [comment]
Yeah, you are right. Will try to fix it.

**Comment by leolorenzoluis** [comment]
@TobiasBreuer I've updated the original library to support Angular 5. https://github.com/leolorenzoluis/xyz.MonacoEditorLoader please see if it works. I've tested it with ng build --prod and it works fine for me.

**Comment by JulCesWhat** [comment]
@TobiasBreuer ...The bug has been fixed. I updated the library to a new version and tested it with my project and it works.
